### ISSUE TITLE
Rcpp error

### ISSUE THREAD

**Issue by ashley-isaac** [m-jahn/SysbioTreemaps#13]
Hi there, thanks for a great package. I successfully created treemaps a month ago with the package, however, I suddenly received an error when running voronoiTreemap().

<simpleError in SysbioTreemaps::cropped_voronoi(sites): function 'enterRNGScope' not provided by package 'Rcpp'>

I tried running install.packages("Rcpp")' and this did not solve the problem. I am running on Ubuntu.
Would you be able to help.

Thanks and looking forward to hearing from you.
Best,
Ashley

**Comment by m-jahn** [comment]
Hi Ashley, thanks for your interest in the package!
The error you see is due to the fact that the package changed recently, dropping the original `lib-cgal` dependency and now depending only on R packages (that is `BH`, boost headers, and the external `cgal4h`, see README). I also encountered the error you see, it's about a random number generator. I think what solves the issue is to
- update all packages, particularly `Rcpp`
- (re)install the `cgal4h` package from gitlab
- (re)install `SysbioTreemaps` from github

**Comment by m-jahn** [comment]
PS: if you're using Rstudio, you can easily update all packages by going to main menu, `Tools` --> `Check for package updates`.
Let me know if it does the trick.

**Comment by ashley-isaac** [comment]
Hi Michael,

Thank you so much for your speedy reply - I was just about to close the issue. I ran:

install.packages("remotes")
remotes::install_github("m-jahn/SysbioTreemaps")

and I guess it updated everything in one go and that solved the issue.
Thanks so much!
