### ISSUE TITLE
bug in the size!

### ISSUE THREAD

**Issue by mir1998** [m-jahn/SysbioTreemaps#25]
I'm using the weightedtreemaps package to visualize a  few datasets of ~30 rows 
I have 2 problems:
1. many times the rstudio crushes in the middle (until I find  a specific seed or choose a high error_tol)
2.  the cell sizes doesnt correlate with the weights of my data 
if you have any suggestions I will reallt appericiate it.
thanks

**Comment by m-jahn** [comment]
Can you try two things:

1. reinstall the latest version of WeightedTreemaps from github using `devtools::install_github()`? I recently introduced a change in how the algorithm converges to the best solution, and this caused many problems. I have reverted to the previous version and it should be stable for data of all sizes
2. post a reproducible example for your problem in 2, that means your code, and the map it produced. Otherwise I can not look into the problem

**Comment by m-jahn** [comment]
Did this solve the problem? Without further information I will close this issue.

**Comment by mir1998** [comment]
I'm working on reinstalling the package
I hope to update you today
many thanks
Miriam

**Comment by mir1998** [comment]
what is the ideal rstudio version for this package?
many thanks
Miriam

**Comment by m-jahn** [comment]
I'm running Rstudio 1.4.1717, but it should not make much of a difference. What  could be useful is to update your R packages. This package is tested against the latest major version of R, 4.0.

**Comment by mir1998** [comment]
I updated now my r version to 4.1.2 and I have problems with the package
installation
Will try now with your version

**Comment by m-jahn** [comment]
I don't think the Rstudio version makes a difference. What errors are you getting? It would be most helpful if you just paste the ouptput from your console here.

**Comment by mir1998** [comment]
Hi
I've fixed it and reinstalled the latest version, now the package works
much better
thank you for this wonderful package and for your kind help
Miriam

**Comment by mir1998** [comment]
when I run with mclapply the rstudio still crushes sometimes

**Comment by m-jahn** [comment]
maybe you can share a reproducible example...
