### ISSUE TITLE
ERROR: dependency ‘BH’ is not available for package ‘WeightedTreemaps’

### ISSUE THREAD

**Issue by cheercheung** [m-jahn/SysbioTreemaps#38]
hello,i tried to install this package in r but failed. 
following is the error.

ERROR: dependency ‘BH’ is not available for package ‘WeightedTreemaps’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/WeightedTreemaps’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/rk/_7pqjx8574l3kvy29jsvbp800000gn/T//RtmpI9HrYc/filee561b9e3337/WeightedTreemaps_0.1.1.tar.gz’ had non-zero exit status

**Comment by m-jahn** [comment]
Hi! The error you get is due to a missing dependency, that means it's not this packages fault but some other R package that `WeightedTreemaps` requires - these are installed beforehand automatically.
I suggest you try to install `BH` manually on your machine. Check what requirements it has; since these are the C++ boost headers, I assume you need a C++ compiler to install it, such as `gcc` on linux.

**Comment by cheercheung** [comment]
hi ，

So appreciate you could reply so quickly!

Thanks for your help!



Cheer
