### ISSUE TITLE
R session crashing when running function voronoiTreemap()

### ISSUE THREAD

**Issue by XiaoHan-Shawn** [m-jahn/SysbioTreemaps#51]
Hi Michael,

Thanks for delivering us such a great package for plotting Voronoi treemaps. I have a thorough learning from the provided tutorial and am very impressed by the idea of procedure separation of generating the fundamental data and adjustable plotting.

However, when I was using function voronoiTreemap() on my data (930 rows, each row per gene), the R session was crashed once and once. Since my data is not very big, I think, and the parameters' setting is general, I don't know why the situation happened. Below is my code and the input data has been attached. 

Your help would be greatly appreciated. Looking forward to your reply!

```
library(WeightedTreemaps)
library(dplyr)
library(openxlsx)

plotdata <- read.xlsx("./o1.VoronoiTreemap-Data.xlsx")

set.seed(666)

tm <- voronoiTreemap(
  data = plotdata,
  levels = c("Regulon","Operon","GeneName"),
  cell_size = "Abs_LogFC",
  sort = T,
  shape = "rectangle",
  custom_color = "LogFC",
  maxIteration = 50,
  error_tol = 0.1
)
```

[o1.VoronoiTreemap-Data.xlsx] (https://github.com/user-attachments/files/17518200/o1.VoronoiTreemap-Data.xlsx)

**Comment by m-jahn** [comment]
thanks for using the package! 
Im gonna look into this issue ASAP.

**Comment by m-jahn** [comment]
I can confirm that it crashes with your data.
I try to find the problem.

**Comment by XiaoHan-Shawn** [comment]
Hi Michael,

Thank you very much for your reply! Following your suggestions on my data's problem, I re-defined the cell size value from 'Abs_LogFC' to '2^Abs_LogFC', and it worked! So, I think, perhaps there are some internal rules that limit the input value range of cell size? I'm not sure.

```
plotdata1 <- read.xlsx("./o1.VoronoiTreemap-Data.xlsx")

plotdata1$Abs_LogFC <- 2 ^ abs(plotdata1$LogFC)
plotdata1 <- plotdata1 %>% arrange(desc(Abs_LogFC))

tm <- voronoiTreemap(
  data = plotdata1,
  levels = c("Regulon","Operon","GeneName"),
  cell_size = "Abs_LogFC",
  sort = T,
  shape = "rectangle" ,
  custom_color = "LogFC",
  seed = 10086,
  maxIteration = 200,
  error_tol = 0.001,
  positioning = c("random","clustered_by_area","clustered_by_area")
)

custom_pal <- colorRampPalette(c("#1565c0","#0277bd","#00838f","#e0e0e0","#f9a825","#ef6c00","#c62828"))(100)

drawTreemap(tm, 
            label_size = c(3,2.5), 
            label_color = c("white","black"),
            label_level = c(1,3),
            
            border = c("black",grey(0.8),grey(0.4)),
            border_size = c(2,1,0.2),
            border_level = c(1,2,3),
            
            legend = T,
            
            color_type = "custom_color",
            color_level = 3,
            color_palette = custom_pal,
            
            custom_range = c(-5,4)
)
```

By the way, as a user of WeightedTreemaps and a bioinformatics learner, I would like to suggest 2 cents regarding the package improvement for your reference. 

1. For color settings, is that possible to make the color vary continuously, not binned, since that the values of many common indicators in biology (e.g. Log2FC for gene expression) are continuous. 
2. For border line settings, is that possible to avoid line overlapping, especially for the color, when plotting border lines from different levels?

Just hope to make the package wider use in biology! Many thanks.

**Comment by m-jahn** [comment]
Hi again, so regarding the stability issues, I identified some problems that can cause the algorithm to crash.
This is particularly the case when you have very few cells with sometimes extreme size difference, as is the case for your data set. Your data has many cells on the second level that have only 1, 2, 3 daughter cells. So re-scaling the data as you did can alleviate this problem to some extent, and also avoiding extremely small values, like two daughter cells with size 10 and size 0.00001.

Nevertheless the algorithm should not crash but stop with error or issue a warning and omit the problematic cell. I will investigate this a bit further.

Regarding your suggestions: 

1. that's a good suggestion, it should be possible to define the number of color steps in the gradient as an extra argument
2. since every cell has its own border, you can not avoid overlapping borders of parents and daughters. However you can define the style of each border level individually, using the `border_color` and `border_size` arguments in a level-specific way:

```
data(mtcars)
mtcars$car_name = gsub(" ", "\n", row.names(mtcars))

tm <- voronoiTreemap(
  data = mtcars,
  levels = c("gear", "car_name"),
  cell_size = "wt",
  shape = "rounded_rect",
  seed = 123
)

drawTreemap(
  tm, title = "treemap 4", label_size = 2,
  color_type = "cell_size", color_level = 2,
  color_palette = heat.colors(10),
  border_size = c(8, 3), border_color = c("white", "black"),
  label_color = grey(0.4),
  title_color = "black", legend = TRUE
)
```

![image](https://github.com/user-attachments/assets/eb4f1cb8-e494-4d88-86f9-c70001082ad2)

**Comment by XiaoHan-Shawn** [comment]
Those are very clear explanations. Thank you so much for solving all my questions!  : )

**Comment by m-jahn** [comment]
@XiaoHan-Shawn 
Check out the new version v0.1.3 which I hope is more stable regarding polygon errors.

**Comment by XiaoHan-Shawn** [comment]
Hi Michael. Just did a quick test based on original data, and it ran very smoothly. Will keep following the updates for WeightedTreemaps. Many thanks!
